apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-cluster-issuer
spec:
  vault:
    server: http://vault.default.svc.cluster.local:8200
    path: pki_int/sign/production-role
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager-vault-role
        serviceAccountRef:
          name: cert-manager-vault-sa
